/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nptabuaofmercruoquvm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdGFidWFvZm1lcmNydW9xdXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NzM4NTksImV4cCI6MjA4NTE0OTg1OX0.flQQpe7xt-7ueFQD-ZGhrp1L-ssAL3ZnqNuqfSRWzjI"